package bsep.kjar;
import com.bsep.securehome.model.DeviceMessage;
import com.bsep.securehome.model.enums.DeviceType;
rule "Air conditionig alarm"
	no-loop
	agenda-group "alarm"
	when
		$deviceMessage: DeviceMessage(type == DeviceType.AIR_CONDITIONING, message == "Air conditioning is in heating mode",  value >= 20)
    then
		Integer v = $deviceMessage.getValue();
		String m = $deviceMessage.getMessage() + ".Temperature:" + String.valueOf(v) + " degree.";
		modify($deviceMessage){
			setAlarm(true),
			setMessage(m);
		}
end


