package bsep.kjar;
import com.bsep.securehome.model.DeviceMessage;
import com.bsep.securehome.model.enums.DeviceType;
rule "Air conditionig alarm"
	no-loop
	agenda-group "alarm"
	when
		$deviceMessage: DeviceMessage(type == DeviceType.AIR_CONDITIONING, message == "Klima je ukljucena u rezimu grejanja",  value >= 23)
    then
		Integer v = $deviceMessage.getValue();
		String m = $deviceMessage.getMessage() + ".Temperatura:" + String.valueOf(v) + " stepeni.";
		modify($deviceMessage){
			setAlarm(true),
			setMessage(m);
		}
end


