package bsep.kjar;
import com.bsep.securehome.model.DeviceMessage;
import com.bsep.securehome.model.enums.DeviceType;
import com.bsep.securehome.dto.AlarmDto;
import com.bsep.securehome.model.enums.LogType;
import com.bsep.securehome.model.Log;
import java.time.LocalDateTime;
import java.util.UUID;


rule "Device alarm"
	no-loop
	agenda-group "alarm"
	when
		$deviceMessage: DeviceMessage()
		$alarms: AlarmDto(type == $deviceMessage.getType(), alarmMessage == $deviceMessage.getMessage())
    then
		modify($deviceMessage){
			setAlarm(true);
		}
end


rule "Log alarm"
	no-loop
	agenda-group "alarm"
	when
		$log: Log(logType == LogType.ERROR)
    then
		DeviceMessage deviceMessage = new DeviceMessage();
		deviceMessage.setId(UUID.randomUUID());
        deviceMessage.setDateTime(LocalDateTime.now());
		deviceMessage.setMessage($log.getMessage());
		deviceMessage.setAlarm(true);
		insert(deviceMessage);
	
end

